/am**:
ros__parameters:
  pink_:
    r: 255
    g: 0
    b: 50
    a: 0
  green_:
    r: 0
    g: 255
    b: 0
    a: 0
  blue_:
    r: 0
    g: 0
    b: 255
    a: 0
  yellow_:
    r: 255
    g: 255
    b: 0
    a: 0